
* Getting started

  Download
  [[https://github.com/vtex-soft/texsupport.elsevier-book/raw/master/release/elsevierbook-project-template.zip][elsevierbook-project-template]]
  package and unzip it.
  Rename the folder =elsevierbook-project-template= to =<your-project-name>=.
  The package is self-contained, which means that once unzipped you can start
  formatting your book straight away. No additional installation steps are required.
  However, you may wish to check the 'Installation' section in the documention.

  Please avoid altering paper dimensions in a ~tex~ file.

* Package content

  - sty/
    - elsevierbook.cls - class file
    - elsevierbook-{a02,a08a,p04}.cls - model class files
  - doc/
     - [[https://github.com/vtex-soft/texsupport.elsevier-book/raw/master/doc/elsbookdoc.pdf][elsbookdoc.pdf]]  - instruction for authors
  - img/ - forder for graphics files: EPS, PDF format
  - book.tex
  - chapter01.tex
  - chapter02.tex
  - [..]

* Submission
  
  Submit one single file as a zip archive. 
  Pack your root folder =<your-project-name>= with files and subfolders.
  Check that subfolder =sty/=, =img/=, or =chapterNN/= (if any) are present in a zip file.

* Bug reports

  Please submit bug report, issues or feature requests on github page
[[https://github.com/vtex-soft/texsupport.elsevier-book/issues]].

